<?php
/**
 * Café query loop image + text + time info
 */
return array(
	'title'         => __( 'Café query loop image + text + time info', 'cafe_cpt' ),
	'categories'    => array( 'cafe-query-loop' ),
	'viewportWidth' => 1200,
	'content'       => "<!-- wp:query {\"queryId\":1,\"query\":{\"perPage\":3,\"pages\":0,\"offset\":0,\"postType\":\"cafe_cpt_item\",\"order\":\"desc\",\"orderBy\":\"date\",\"author\":\"\",\"search\":\"\",\"exclude\":[],\"sticky\":\"\",\"inherit\":false},\"align\":\"wide\"} -->\n<div class=\"wp-block-query alignwide\"><!-- wp:post-template {\"lock\":{\"move\":true,\"remove\":true}} -->\n<!-- wp:columns {\"style\":{\"spacing\":{\"padding\":{\"top\":\"30px\",\"right\":\"30px\",\"bottom\":\"30px\",\"left\":\"30px\"},\"blockGap\":\"50px\"}}} -->\n<div class=\"wp-block-columns\" style=\"padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px\"><!-- wp:column {\"width\":\"25%\"} -->\n<div class=\"wp-block-column\" style=\"flex-basis:25%\"><!-- wp:post-featured-image {\"isLink\":true,\"width\":\"\",\"height\":\"160px\",\"style\":{\"spacing\":{\"margin\":{\"top\":\"30px\"}}}} /--></div>\n<!-- /wp:column -->\n\n<!-- wp:column {\"verticalAlignment\":\"top\",\"width\":\"50%\",\"style\":{\"spacing\":{\"padding\":{\"top\":\"0px\",\"right\":\"0px\",\"bottom\":\"0px\",\"left\":\"0px\"},\"blockGap\":\"0px\"},\"border\":{\"width\":\"0px\",\"style\":\"none\"}},\"layout\":{\"inherit\":false}} -->\n<div class=\"wp-block-column is-vertically-aligned-top\" style=\"border-style:none;border-width:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;flex-basis:50%\"><!-- wp:post-title /-->\n\n<!-- wp:acf/cafe-description {\"id\":\"block_627d4b311ff9b\",\"name\":\"acf/cafe-description\",\"data\":[],\"align\":\"\",\"mode\":\"preview\",\"align_text\":\"left\"} /--></div>\n<!-- /wp:column -->\n\n<!-- wp:column {\"width\":\"25%\"} -->\n<div class=\"wp-block-column\" style=\"flex-basis:25%\"><!-- wp:acf/opening-hours {\"id\":\"block_627d4f0684f92\",\"name\":\"acf/opening-hours\",\"data\":[],\"align\":\"\",\"mode\":\"preview\",\"align_text\":\"left\"} /--></div>\n<!-- /wp:column --></div>\n<!-- /wp:columns -->\n<!-- /wp:post-template -->\n\n<!-- wp:query-pagination {\"layout\":{\"type\":\"flex\",\"justifyContent\":\"center\"}} -->\n<!-- wp:query-pagination-previous /-->\n\n<!-- wp:query-pagination-numbers /-->\n\n<!-- wp:query-pagination-next /-->\n<!-- /wp:query-pagination -->\n\n<!-- wp:query-no-results -->\n<!-- wp:paragraph {\"placeholder\":\"Añade un texto o bloques que se mostrarán cuando no devuelva resultados la consulta.\"} -->\n<p></p>\n<!-- /wp:paragraph -->\n<!-- /wp:query-no-results --></div>\n<!-- /wp:query -->"
);
